# Change these first
owner: Sid220 # Your GitHub organization or username, where this repository lives
repo: sid220.github.io # The name of this repository

sites:
  - name: Vestal
    url: https://www.vestal.ml
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  name: Vestal <i>Status</i>
  logoUrl: https://www.vestal.ml/The%20Sid%20Projects%20Logo.jpg
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vestal.ml
  # baseUrl: /your-repo-name
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.vestal.ml/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
